name: CI-services
on: push

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      redis:
        image: redis:5
        ports:
        - 6379/tcp

      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        ports:
        - 9200/tcp
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10

      datastore:
        image: google/cloud-sdk

      pubsub:
        image: google/cloud-sdk

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Check running services
        run: ./test.sh