name: CI-services
on: [push]

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        env:
          discovery.type: single-node
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
        - 9200:9200

      redis:
        image: redis
        options: --entrypoint redis-server

      datastore:
        image: google/cloud-sdk

      pubsub:
        image: google/cloud-sdk

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Check running services
        run: |
          sleep 60
          ./test.sh