name: CI-services
on: [push]

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        env:
          discovery.type: single-node
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
        - 9200:9200

      redis:
        image: redis
        options: --entrypoint redis-server
        ports:
        - "6379:6379"

      datastore:
        image: singularities/datastore-emulator
        env:
          DATASTORE_PROJECT_ID: dev
          DATASTORE_LISTEN_ADDRESS: 0.0.0.0:8081
        options: >-
          --health-cmd "curl http://localhost:8081"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
        - "8081:8081"

      pubsub:
        image: knarz/pubsub-emulator
        options: >-
          --health-cmd "curl http://localhost:8085"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
        - "8085:8085"

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Check Elastic Search
        run: curl http://localhost:9200/_cluster/health
          
      - name: Check Datastore
        run: curl http://localhost:8081

      - name: Check PubSub
        run: curl http://localhost:8085

      - name: Check Memcache
        run: sudo apt-get install netcat && nc localhost 6379