name: CI-services
on: push

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        image: redis:5
      elastic_search:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
      datastore:
        image: google/cloud-sdk
      pubsub:
        image: google/cloud-sdk

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Check running services
        run: ./test.sh
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379